### ISSUE TITLE
Lambda Python Code Missing

### ISSUE THREAD

**Issue by miztiik** [cdk-patterns/serverless#52]
In this pattern - https://github.com/cdk-patterns/serverless/blob/master/the-dynamo-streamer/python/lambdas/subscribe/lambda.js

The nodejs code is uploaded to the python directory

**Comment by cdk-patterns** [comment]
Thanks for opening this issue. To give some background.

Cdkpatterns started as TypeScript only. After seeing that a sizeable % of the AWS CDK dev community were using Python I made a Python CDK version of every pattern.

So that I wasn’t maintaining 2 completely separate codebases it seemed a fair tradeoff to reuse the JavaScript compiled node lambdas inside the Python CDK implementations.

This was because the lambdas were mostly super simple and it makes the Python/TypeScript versions effectively identical outside of any bugs in Python CDK. 

Note - The Lambda Trilogy is an exception and is pure Python because that pattern was more about the lambdas than the CDK.

However, that is how we got to where we are today. From here the decision that needs to be made is if I need to rewrite all of the lambdas in the Python CDK implementations in Python.

It would add a large amount of extra effort on my part with new patterns since I would not be able to reuse anything from the TypeScript versions.

On the flip side if Python developers do not enjoy learning from the patterns with JS lambdas included I am currently wasting effort.

Now that you know this is a deliberate compromise, how do you feel about JS lambdas in the Python CDK implementations?

Thanks,
Matt

**Comment by miztiik** [comment]
Thanks for the clarification.
As someone, who spends a lot of time with python, It is not too difficult to follow the nodejs(simple examples in the cdk-pattern repo) code.

The patterns are going to evolve over time, Somewhere alone the line, a pattern will be easier to implement in one language compared to the other.(probably `async` maybe? Does aysnc in lambda make it lambda-lith?!?!).

Aside from that, from a _idealistic_ perspective, Can we add this to the main readme, so that the community will be aware of this deliberate compromise.

**Comment by cdk-patterns** [comment]
Absolutely, that's a miss.

I will also over time look at the established patterns and start migrating some to pure python. It's definitely easier to migrate once they are launched than developing two separate apps in two different languages at launch time.

I will close this issue and add a section outlining what people can expect from the python versions today.

**Comment by cdk-patterns** [comment]
Also, since that lambda was so simple I just migrated it to python.

**Comment by cdk-patterns** [comment]
https://github.com/cdk-patterns/serverless#2-download-pattern-in-python-or-typescript-cdk wording updated
